name: Build

on:
  push:
    branches-ignore:
      - master

jobs:
  production_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci --no-optional
    - run: npm run lint
    - run: npm test
    - run: npx codecov -t ${{ secrets.CODECOV_TOKEN }}
    - run: npm run build:client:prod
    - run: npm run build:server:prod
